name: 'Test report'
description: 'Upload test report'
inputs:
  report_name:
    description: 'Report name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.report_name }}
        path: /app/reports/
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '/app/reports/report.xml'
        detailed_summary: true
        include_passed: false
        check_name: ${{ inputs.report_name }}
        annotate_only: true
