FROM ghcr.io/dpc-sdp/bay/mariadb:6.x 

ARG DATA_DIR=/tmp/data
ARG DB_FILE=db.sql

COPY $DATA_DIR /var/lib/mysql
COPY $DB_FILE /var/tmp/db.sql

USER root

RUN chown -R mysql /var/lib/mysql \
    && chgrp -R mysql /var/lib/mysql \
    && /bin/fix-permissions /var/lib/mysql

USER mysql
ENV MARIADB_INIT_WAIT_SECONDS=80
ENV MARIADB_INIT_PERIOD_SECOND=2
