name: Container action
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PWD
        run: echo $(pwd)
      - name: Hello world action step
        # Uses an action in the root directory
        uses: dpc-sdp/action-container@main
        id: hello
        with:
          # Explicit input from the caller.
          who-to-greet: ${{ inputs.who-to-greet }}
          # Inherited secret from the caller.
          my-other-var: ${{ secrets.TEST_VAR }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

