name: e2e_be_core

on:
  workflow_call:
    inputs:
      be_url:
        description: The backend URL for testing
        type: string
        required: true
        default: ""
      project:
        description: Lagoon project name
        type: string
        required: true
        default: ""
      browser:
        description: Browser, default to headless Chrome.
        type: string
        default: "chrome"
      tag:
        description: SDP testing Docker image tag
        type: string
        required: false
        default: migration

jobs:
  check_pr:
    name: check_pr
    runs-on: biggy
    container:
      image: docker://sdptestautomation/e2e:${{ inputs.tag }}
      credentials:
        username: ${{ secrets.E2E_DOCKERHUB_USERNAME }}
        password: ${{ secrets.E2E_DOCKERHUB_PASSWORD }}
    defaults:
      run:
        shell: bash
    outputs:
      skip_pr: ${{ steps.check-pr.outputs.SKIP_PR }}
    steps:
      - name: Check if it's PR env backend
        id: check-pr
        run: |
          PR_ENV_REGEX=".*.pr-"
          if [[ $(expr match "${{ inputs.be_url }}" $PR_ENV_REGEX) != 0 ]]; then
            echo 'SKIP_PR=" and not @skip-pr"' >> $GITHUB_OUTPUT
            echo "PR env detected - adding @skip-pr tag to skip tests"
          else
            echo 'SKIP_PR=""' >> $GITHUB_OUTPUT
            echo "PR env not detected"
          fi
  e2e_be_core:      
    name: Run E2E BE
    secrets: inherit
    uses: dpc-sdp/github-actions/.github/workflows/run_e2e_be.yml@main
    with:
        tags: "(@core) and @regression${{ needs.check_pr.outputs.skip_pr }}"
        be_url: ${{ inputs.be_url }}
        project: ${{ inputs.project }}
        browser: ${{ inputs.browser }}
        test_id: "e2e_be"
        test_type: "fixture"