name: export_config

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name to export config and push changes (e.g., release/SCFA-1234)"
        required: true
        type: string
      uat_push:
        description: "Push to UAT flag"
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  export_config:
    name: Export Config and Push to UAT
    runs-on: biggy
    container:
      image: ghcr.io/dpc-sdp/bay/ci-builder:5.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Uncomment database snapshot environment variable
        run: |
          sed -i 's|# DB_IMAGE_SNAPSHOT|DB_IMAGE_SNAPSHOT|' .env

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.DEPLOY_USER_EMAIL }}" \
            && git config --global user.name "${{ secrets.DEPLOY_USER_NAME }}"

      - name: Adjust permissions and copy repo
        run: |
          chown -R $(id -u):$(id -g) $PWD
          cp -R ${GITHUB_WORKSPACE} /app

      - name: Run export script
        run: |
          cd /app
          bash scripts/eexport_config_push_uat.sh "${{ inputs.branch_name }}"

      - name: Notify completion
        if: success()
        run: |
          echo "Export config completed and pushed to branch ${{ inputs.branch_name }}."
