name: export_config

on: workflow_call

jobs:
  build_tide:
    name: export_config
    runs-on: biggy
    container:
      image: ghcr.io/dpc-sdp/bay/ci-builder:5.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # GitHub Actions does not support cloning to a custom path.
      - name: Copy repo
        run: |
          cp -R /__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/} /app
      - name: Run export script
        run: |
          /app/.circleci/export-config.sh