name: force_push_to_uat

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name to push changes to (e.g., release/SCFA-1234)"
        required: true
        type: string

jobs:
  force_push_to_uat:
    name: Force Push Branch to UAT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full branch history

      - name: Fetch and Pull Latest Changes
        run: |
          git fetch origin "${{ inputs.branch_name }}"
          git checkout "${{ inputs.branch_name }}"
          git pull origin "${{ inputs.branch_name }}" # Ensure latest commits are present

      - name: Log Branch State
        run: |
          echo "Branch state before force-push:"
          git log --oneline -5

      - name: Force Push to UAT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin "${{ inputs.branch_name }}:uat" --force

      - name: Notify Completion
        if: success()
        run: echo "Branch ${{ inputs.branch_name }} has been force pushed to UAT."
