name: post_jira_comment

on:
  workflow_call:
    inputs:
      jira_id:
        type: string
        required: true
        default: ""
      comment:
        type: string
        required: true
        default: ""


jobs:
  notify_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Post JIRA Comment
        id: post_jira_comment
        env:
          JIRA_USERNAME: ${{ secrets.TEST_JIRA_USERNAME }}  # Jira username from secrets
          JIRA_PASSWORD: ${{ secrets.TEST_JIRA_PASSWORD }}  # Jira password from secrets
        run: |
          echo "JIRA_ID=${{ inputs.jira_id }}" >> $GITHUB_ENV
          echo "COMMENT=${{ inputs.comment }}" >> $GITHUB_ENV
          echo -e "${JIRA_ID}"
          echo -e "${COMMENT}"
          # Define the JIRA comment API endpoint
          JIRA_API_URL="https://digital-vic.atlassian.net/rest/api/2/issue/${JIRA_ID}/comment"

          # Post the comment to JIRA using basic auth with username and password
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -u "${JIRA_USERNAME}:${JIRA_PASSWORD}" \
            --data "{\"body\": \"${COMMENT}\"}" \
            "${JIRA_API_URL}")

          http_code="${response:(-3)}"  # Extract HTTP status code (last 3 characters)
          response_body="${response:0:-3}"  # The response body

          # Handle the API response
          if [ "$http_code" -eq 201 ]; then
            echo "Comment posted successfully to Jira issue ${JIRA_ID}"
          else
            echo "Failed to post comment to Jira issue ${JIRA_ID}. HTTP Code: $http_code"
            echo "Response Body: $response_body"
          fi
