name: Reusable workflow to build MySQL database images 

on:
  workflow_call:
    inputs:
      be_url:
        description: 'Backend URL'
        required: false
        type: string
      fe_url:
        description: 'Frontend URL'
        required: false
        type: string
      project:
        description: 'Project'
        required: false
        type: string
      s3_uri:
        description: 'S3 URI'
        required: true
        type: string
      file_name:
        description: 'File Name in S3'
        required: true
        type: string
        
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true


env:
  REGISTRY: ghcr.io
    
jobs:
  db_image_build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Checkout Dockerfile from central repository
        uses: actions/checkout@v2
        with:
          repository: 'dpc-sdp/bay' 
          ref: 'feature/rmk-db-trigger' 
          path: 'bay'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Extract repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}/db
          tags: |
            type=ref,event=branch

      - name: Build and push multi-arch Docker image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./bay/images/mariadb-ci 
          file: ./bay/images/mariadb-ci/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}/db:production-latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64  # Add other platforms if needed
          build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            S3_URI=${{ inputs.s3_uri }}
            FILE_NAME=${{ inputs.file_name }}         
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
  
  notify_slack:
    runs-on: ubuntu-latest
    needs: [db_image_build_push] 
    if: ${{ always() }}  
    steps:
      - name: Send Notification to Slack on Failure
        if: ${{ needs.db_image_build_push.result == 'failure' }} 
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.db_image_build_push.result }}
          text: 'Attention: The db-trigger workflow has FAILED in project "${{ inputs.project }}" for repo "${{ github.repository }}"!'
          fields: 'project: ${{ inputs.project }}, repo: ${ { github.repository }}'
          mention: 'here'
          author_name: 'DPC TEAM'
          channel: '#dpc-events'
          color: 'danger'  
          if_mention: 'always'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Notification to Slack on Success
        if: ${{ needs.db_image_build_push.result == 'success' }}  
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.db_image_build_push.result }}
          text: 'The db-trigger workflow for project "${{ inputs.project }}" in repository "${{ github.repository }}" has succeeded.'
          fields: 'project: ${{ inputs.project }}, repo: ${ { github.repository }}'
          mention: 'channel'
          author_name: 'DPC TEAM'
          channel: '#dpc-events'
          color: 'good'  
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}




