name: test_notify_jira

on:
  workflow_call:
    inputs:
      status:
        type: string
        required: true
        default: ""

jobs:
  notify_jira:
    runs-on: ubuntu-latest
    outputs:
      jira_id: ${{ steps.extract_jira_id.outputs.jira_id }}
      comment: ${{ steps.prepare_jira_comment.outputs.comment }}
    steps:
      - name: Extract JIRA ID from the commit message
        id: extract_jira_id
        run: |
          # Fetch commit message from the GitHub API
          commit_info=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }})

          # Check if curl was successful
          if [ $? -ne 0 ]; then
            echo "Failed to fetch commit message."
            exit 0  # Exit gracefully on curl failure
          fi

          commit_message=$(echo "$commit_info" | jq -r '.commit.message')
  
          # Extract JIRA ID
          JIRA_ID=$(echo "$commit_message" | grep -oE 'SCFA-[0-9]{1,5}' || true)  # Prevents non-zero exit code
  
          # Check if JIRA ID is found
          if [ -z "$JIRA_ID" ]; then
            echo "No JIRA ID found in commit message: $commit_message"
          else
            echo "Extracted JIRA ID: $JIRA_ID"
            echo "JIRA_ID=$JIRA_ID" >> $GITHUB_ENV
            echo "::set-output name=jira_id::$JIRA_ID"
          fi
  

      - name: Set the workflow status
        id: set_e2e_status
        if: env.JIRA_ID != ''
        run: |
          echo 'STATUS=${{ inputs.status }}' >> $GITHUB_ENV
          echo "Overall workflow status: ${STATUS}"

      - name: Prepare JIRA Comment
        id: prepare_jira_comment
        if: env.JIRA_ID != ''
        env:
          WORKFLOW_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"  # Link to the workflow run
        run: |
          echo "Preparing JIRA comment..."

          # Determine the branch name from the Git reference
          GIT_BRANCH=${GITHUB_REF##*/}

          # Construct the comment template
          COMMENT="E2E Test - ${STATUS} on branch ${GIT_BRANCH}\n"
          COMMENT+="Workflow URL: $WORKFLOW_LINK"

          # Print the comment to the console for debugging
          echo -e "COMMENT:\n${COMMENT}"
          echo "COMMENT=$COMMENT" >> $GITHUB_ENV
          echo "::set-output name=comment::$COMMENT"

      # - name: Post JIRA Comment
      #   if: env.JIRA_ID != ''
      #   uses: ./.github/workflows/post_jira_comment.yml
      #   with:
      #     JIRA_ID: ${{ env.JIRA_ID }}
      #     COMMENT: ${{ env.COMMENT }}

  post_jira_comment:
    uses: ./.github/workflows/post_jira_comment.yml
    needs: [notify_jira]
    secrets: inherit
    with:
      jira_id: ${{ needs.notify_jira.outputs.jira_id }}
      comment: ${{ needs.notify_jira.outputs.comment }}

