name: Terraform diffscheck
on:
  workflow_call:
    inputs:
      aws_default_region:
        description: AWS region for the state file
        type: string
        required: false
        default: ap-southeast-2
      slack_channel:
        type: string
        required: false
        default: "ops"

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
  EC_API_KEY: ${{ secrets.EC_API_KEY }}
  GITHUB_OWNER: ${{ vars.TF_GITHUB_OWNER }}
  SUMOLOGIC_ACCESSID: ${{ secrets.SUMOLOGIC_ACCESSID }}
  SUMOLOGIC_ACCESSKEY: ${{ secrets.SUMOLOGIC_ACCESSKEY }}
  CONSTELLIX_API_KEY:  ${{ secrets.CONSTELLIX_API_KEY }}
  CONSTELLIX_SECRET_KEY:  ${{ secrets.CONSTELLIX_SECRET_KEY }}

jobs:
  diffscheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

#      - name: Terraform fmt
#        id: fmt
#        run: terraform fmt -check

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan -input=false -out=tfplan -no-color -detailed-exitcode

      - name: No diff - exit
        id: no_diff_exit
        if: steps.plan.outputs.exitcode != 2
        run: echo "No diffs detected - terminating."

      - name: Send Slack notification
        id: notify_slack
        uses: slackapi/slack-github-action@v1.26.0
        if: steps.plan.outputs.exitcode == 2
        env:
          REPO_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.event.repository.html_url }}
          SLACK_BOT_TOKEN: ${{ secrets.TF_NOTIFICATIONS_SLACK_TOKEN }}
          LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          channel-id: ${{ inputs.slack_channel }}
          slack-message: "Diffs detected in ${{ env.REPO_NAME }}\n${{ env.LINK }}"