name: tide_build

on: 
  workflow_call:
    inputs:
      module_build:
        description: Set to true to install dev-tools before building the project.
        type: string
        required: false
        default: false
      runner:
        description: Name of the runner instance to use.
        type: string
        required: false
        default: biggy

env:
  REGISTRY: ghcr.io

jobs:
  build_tide:
    name: tide_build
    runs-on: ${{ inputs.runner }}
    container:
      image: ghcr.io/dpc-sdp/bay/ci-builder:5.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Uncomment database snapshot environment variable
        if: ${{ inputs.module_build != 'true' }}
        run: |
          sed -i 's|# DB_IMAGE_SNAPSHOT|DB_IMAGE_SNAPSHOT|' .env
      - name: Install dev-tools
        if: ${{ inputs.module_build == 'true' }}
        run: |
          echo ==> Installing dev-tools...
          if [ -f "./dev-tools.sh" ] && [ ! "$DEV_TOOLS" ]; then ./dev-tools.sh; fi
      # GitHub Actions does not support cloning to a custom path.
      - name: Copy repo
        run: |
          cp -R /__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/} /app
      - name: Run build script
        run: |
          /app/.circleci/build.sh
      - name: Run test script
        if: always()
        run: |
          /app/.circleci/test.sh
      - name: Copy artifacts
        if: always()
        run: |
          /app/.circleci/test-artifacts.sh
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: behat-results
          path: /tmp/artifacts